---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    project: console
    provider: fabric8
    version: 2.2.105
    group: io.fabric8.apps
    package: console-kubernetes
  name: fabric8
spec:
  deprecatedPublicIPs: []
  externalIPs: []
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    project: console
    provider: fabric8
    group: io.fabric8.apps
  type: ClusterIP
